name: gad_2023_early_2
description: Flutter application for a marketplace

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  http: ^0.13.6
  redux_epics: ^0.15.1
  redux: ^5.0.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - .env