name: Check quality of code
on:
  push:

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Unlock Secrets
        run: echo "UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }}" > .env

      - name: Install flutter
        uses: subosito/flutter-action@v2

      - name: Check format
        run: dart format --line-length 120 --set-exit-if-changed ./lib

      - name: Analyze code
        run: flutter analyze